// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYl-ICnin742PpZnW8wetR-EY0OkXTRvw',
    appId: '1:989179799679:web:1c1a98d7b5743bcca1b74a',
    messagingSenderId: '989179799679',
    projectId: 'flutter-sih-f76f6',
    authDomain: 'flutter-sih-f76f6.firebaseapp.com',
    storageBucket: 'flutter-sih-f76f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChotp8Cp-82C0_QNesHr3eAPdGxwlTdjM',
    appId: '1:989179799679:android:58fa3e204e42ab2ea1b74a',
    messagingSenderId: '989179799679',
    projectId: 'flutter-sih-f76f6',
    storageBucket: 'flutter-sih-f76f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW915DuDHWjAGwd7y01x4F_zqTSSGzbT8',
    appId: '1:989179799679:ios:4194b31cd0e68cb4a1b74a',
    messagingSenderId: '989179799679',
    projectId: 'flutter-sih-f76f6',
    storageBucket: 'flutter-sih-f76f6.appspot.com',
    iosBundleId: 'com.example.bookMySlot',
  );
}
